// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance_defaults.sql

package database

import (
	"context"
)

const getDefaults = `-- name: GetDefaults :one
SELECT id, image, cpu_request, memory_request, cpu_limit, memory_limit, storage_size, ingress_domain, updated_at FROM instance_defaults LIMIT 1
`

func (q *Queries) GetDefaults(ctx context.Context) (InstanceDefault, error) {
	row := q.db.QueryRow(ctx, getDefaults)
	var i InstanceDefault
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.CpuRequest,
		&i.MemoryRequest,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.StorageSize,
		&i.IngressDomain,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDefaults = `-- name: UpdateDefaults :one
UPDATE instance_defaults SET
    image = $1,
    cpu_request = $2,
    memory_request = $3,
    cpu_limit = $4,
    memory_limit = $5,
    storage_size = $6,
    ingress_domain = $7,
    updated_at = now()
RETURNING id, image, cpu_request, memory_request, cpu_limit, memory_limit, storage_size, ingress_domain, updated_at
`

type UpdateDefaultsParams struct {
	Image         string `json:"image"`
	CpuRequest    string `json:"cpu_request"`
	MemoryRequest string `json:"memory_request"`
	CpuLimit      string `json:"cpu_limit"`
	MemoryLimit   string `json:"memory_limit"`
	StorageSize   string `json:"storage_size"`
	IngressDomain string `json:"ingress_domain"`
}

func (q *Queries) UpdateDefaults(ctx context.Context, arg UpdateDefaultsParams) (InstanceDefault, error) {
	row := q.db.QueryRow(ctx, updateDefaults,
		arg.Image,
		arg.CpuRequest,
		arg.MemoryRequest,
		arg.CpuLimit,
		arg.MemoryLimit,
		arg.StorageSize,
		arg.IngressDomain,
	)
	var i InstanceDefault
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.CpuRequest,
		&i.MemoryRequest,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.StorageSize,
		&i.IngressDomain,
		&i.UpdatedAt,
	)
	return i, err
}
