// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InstanceDefault struct {
	ID            pgtype.UUID        `json:"id"`
	Image         string             `json:"image"`
	CpuRequest    string             `json:"cpu_request"`
	MemoryRequest string             `json:"memory_request"`
	CpuLimit      string             `json:"cpu_limit"`
	MemoryLimit   string             `json:"memory_limit"`
	StorageSize   string             `json:"storage_size"`
	IngressDomain string             `json:"ingress_domain"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	Picture       pgtype.Text        `json:"picture"`
	Role          string             `json:"role"`
	OidcSubject   string             `json:"oidc_subject"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	InstanceLimit int32              `json:"instance_limit"`
}
