// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, picture, role, oidc_subject)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, picture, role, oidc_subject, created_at, updated_at, instance_limit
`

type CreateUserParams struct {
	Email       string      `json:"email"`
	Name        string      `json:"name"`
	Picture     pgtype.Text `json:"picture"`
	Role        string      `json:"role"`
	OidcSubject string      `json:"oidc_subject"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Picture,
		arg.Role,
		arg.OidcSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.Role,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceLimit,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, picture, role, oidc_subject, created_at, updated_at, instance_limit FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.Role,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceLimit,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, picture, role, oidc_subject, created_at, updated_at, instance_limit FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.Role,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceLimit,
	)
	return i, err
}

const getUserByOIDCSubject = `-- name: GetUserByOIDCSubject :one
SELECT id, email, name, picture, role, oidc_subject, created_at, updated_at, instance_limit FROM users WHERE oidc_subject = $1
`

func (q *Queries) GetUserByOIDCSubject(ctx context.Context, oidcSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCSubject, oidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.Role,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceLimit,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, picture, role, oidc_subject, created_at, updated_at, instance_limit FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Picture,
			&i.Role,
			&i.OidcSubject,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstanceLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = COALESCE($2, email),
    name = COALESCE($3, name),
    picture = COALESCE($4, picture),
    role = COALESCE($5, role),
    instance_limit = COALESCE($6, instance_limit),
    updated_at = now()
WHERE id = $1
RETURNING id, email, name, picture, role, oidc_subject, created_at, updated_at, instance_limit
`

type UpdateUserParams struct {
	ID            pgtype.UUID `json:"id"`
	Email         pgtype.Text `json:"email"`
	Name          pgtype.Text `json:"name"`
	Picture       pgtype.Text `json:"picture"`
	Role          pgtype.Text `json:"role"`
	InstanceLimit pgtype.Int4 `json:"instance_limit"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Picture,
		arg.Role,
		arg.InstanceLimit,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.Role,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceLimit,
	)
	return i, err
}
