services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_SHELL: ${SHELL}
    volumes:
      # Mount the parent of the project to the workspaces directory so the
      # devcontainer can "see" sibling projects at /workspaces/*.  This provides
      # less isolation (e.g. when running claude in yolo mode), but is useful
      # when doing things like running deploy.sh in the cloudops repo to
      # manually deploy another project.
      #
      - ../..:/workspaces:cached
      # Alternative for full project isolation, also see devcontainer.json:workspaceFolder
      # - ..:/workspace:cached

      # Mount the home directory to a volume to preserve terminal history across
      # rebuilds.  Safe to comment out to have a fresh slate each rebuild.  Note
      # that when docker mounts to a new empty volume, it copies files from the
      # container's mount point (/home/vscode) into the volume.  Thus to pick up
      # any changes you make to the Dockerfile that affect the contents of the
      # home directory, you will have to delete the volume/container and rebuild
      #
      - home_directory:/home/vscode
    command: sleep infinity
    environment:
      EDITOR: code -w

    # Setting VAR in project_root/.devcontaner/.env allows referencing it in this file with ${VAR}
    # Setting VAR in project_root/.env allows referencing VAR in this container's runtime environment,
    # e.g. to set vars above in `environment:` vars needed for your terminal usage and application
    # The precedence of env_files are bottom-up, so VARs in .env win
    #
    env_file:
      - path: ../.env.example
        required: false # (optional, ignored if missing)
      - path: ../.env
        required: false # (optional, ignored if missing)

    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "clawbake.127-0-0-1.nip.io:host-gateway"

    # All host ports become localhost inside the container
    # Everything just works, no per-port config
    # Breaks container network isolation entirely, may conflict with other things, extra_hosts and port forwarding stop working
    #
    # network_mode: host

    # Puts k3d on the same network as the devcontainer, allowing one to reach
    # the k3d loadbalancer container from within a devcontainer by its Docker
    # DNS name: k3d-clawbake-serverlb:80 The extra_hosts above also maps dns
    # names so that the loadbalancer can forward by Host to the correct Service
    # 
    # also needs networks: section at top level
    #
    networks:
      - default
      - k3d

# Creats the network that k3d then attaches to.  Needed for the networks: section in the devcontainer service above
#
networks:
  k3d:
    external: false
    name: k3d-clawbake

volumes:
  home_directory:
