apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clawbake.fullname" . }}
  labels:
    {{- include "clawbake.labels" . | nindent 4 }}
data:
  instance-default-image: {{ .Values.instanceDefaults.image }}
  instance-cpu-request: {{ .Values.instanceDefaults.cpuRequest }}
  instance-memory-request: {{ .Values.instanceDefaults.memoryRequest }}
  instance-cpu-limit: {{ .Values.instanceDefaults.cpuLimit }}
  instance-memory-limit: {{ .Values.instanceDefaults.memoryLimit }}
  instance-storage-size: {{ .Values.instanceDefaults.storageSize }}
  instance-gateway-config: {{ .Values.instanceDefaults.gatewayConfig | quote }}
  instance-ttyd-enabled: {{ .Values.instanceDefaults.ttyd.enabled | quote }}
  instance-ttyd-image: {{ .Values.instanceDefaults.ttyd.image }}
  instance-tui-enabled: {{ and .Values.instanceDefaults.ttyd.enabled .Values.instanceDefaults.ttyd.tui.enabled | quote }}
  instance-tui-port: {{ .Values.instanceDefaults.ttyd.tui.port | quote }}
  instance-tui-command: {{ .Values.instanceDefaults.ttyd.tui.command | quote }}
  instance-shell-enabled: {{ and .Values.instanceDefaults.ttyd.enabled .Values.instanceDefaults.ttyd.shell.enabled | quote }}
  instance-shell-port: {{ .Values.instanceDefaults.ttyd.shell.port | quote }}
  instance-shell-command: {{ .Values.instanceDefaults.ttyd.shell.command | quote }}
