apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clawbake.fullname" . }}
  labels:
    {{- include "clawbake.labels" . | nindent 4 }}
data:
  instance-default-image: {{ .Values.instanceDefaults.image }}
  instance-cpu-request: {{ .Values.instanceDefaults.cpuRequest }}
  instance-memory-request: {{ .Values.instanceDefaults.memoryRequest }}
  instance-cpu-limit: {{ .Values.instanceDefaults.cpuLimit }}
  instance-memory-limit: {{ .Values.instanceDefaults.memoryLimit }}
  instance-storage-size: {{ .Values.instanceDefaults.storageSize }}
  instance-gateway-config: {{ .Values.instanceDefaults.gatewayConfig | quote }}
  instance-ttyd-enabled: {{ .Values.instanceDefaults.ttyd.enabled | quote }}
  instance-ttyd-image: {{ .Values.instanceDefaults.ttyd.image }}
  instance-ttyd-port: {{ .Values.instanceDefaults.ttyd.port | quote }}
  instance-ttyd-command: {{ .Values.instanceDefaults.ttyd.command | quote }}
  instance-ttyd-cpu-request: {{ .Values.instanceDefaults.ttyd.cpuRequest }}
  instance-ttyd-memory-request: {{ .Values.instanceDefaults.ttyd.memoryRequest }}
  instance-ttyd-cpu-limit: {{ .Values.instanceDefaults.ttyd.cpuLimit }}
  instance-ttyd-memory-limit: {{ .Values.instanceDefaults.ttyd.memoryLimit }}

